# Generated by Django 2.0.4 on 2018-05-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0002_auto_20180524_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.Attraction'),
        ),
    ]
