# Generated by Django 2.0.4 on 2018-05-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        ('comments', '0001_initial'),
        ('core', '0003_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='evaluations',
            field=models.ManyToManyField(to='evaluations.Evaluation'),
        ),
    ]
